Repository Rajkumar-justcoder/Animated-name, pull requests merged in 2022-10, with the labels that each got.

#7 Different section with different contributor name with scroll effect
  index.html
  name.css
  script.js
Labels: Hacktoberfest Accepted

#12 Update index.html
  index.html
Labels: Hacktoberfest-accepted

#22 feat: set an array of objects for names
  index.html
  names.js
  script.js
Labels: hacktoberfest, Hacktoberfest-accepted
